# Generated by Django 5.2.5 on 2025-08-21 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moj_projekt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
