services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    stop_signal: SIGINT
    volumes:
      - ./python:/app
    ports:
      - '5001:5001'
    entrypoint: [ "python", "app.py","runserver" ]


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres/data

volumes:
  db_data: