services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn projectname.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=moj_projekt.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: